// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvR-CE_bre4aR5VUzksnBuURZsnDHvlnk',
    appId: '1:98254208989:web:66f37c26ad3c96fbb74034',
    messagingSenderId: '98254208989',
    projectId: 'flutterbutter-ce9b3',
    authDomain: 'flutterbutter-ce9b3.firebaseapp.com',
    databaseURL: 'https://flutterbutter-ce9b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterbutter-ce9b3.appspot.com',
    measurementId: 'G-6W43C2V9E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB72sSI0Dzx_YItExSq4BHCu4tpd2PnNXY',
    appId: '1:98254208989:android:1aa84d9521e9549ab74034',
    messagingSenderId: '98254208989',
    projectId: 'flutterbutter-ce9b3',
    databaseURL: 'https://flutterbutter-ce9b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterbutter-ce9b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt3DnVP0teU-tT7sMgvcBw1FB6E2ycTmA',
    appId: '1:98254208989:ios:438bc30c974d1592b74034',
    messagingSenderId: '98254208989',
    projectId: 'flutterbutter-ce9b3',
    databaseURL: 'https://flutterbutter-ce9b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterbutter-ce9b3.appspot.com',
    iosClientId: '98254208989-9m7j6v5vuulnuedc0sc3l3evat67pr5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt3DnVP0teU-tT7sMgvcBw1FB6E2ycTmA',
    appId: '1:98254208989:ios:438bc30c974d1592b74034',
    messagingSenderId: '98254208989',
    projectId: 'flutterbutter-ce9b3',
    databaseURL: 'https://flutterbutter-ce9b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterbutter-ce9b3.appspot.com',
    iosClientId: '98254208989-9m7j6v5vuulnuedc0sc3l3evat67pr5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbutter',
  );
}
